apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::601125232298:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-62I2A0LG5S8Q
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::601125232298:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-08T19:21:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1217"
  uid: 9050945b-f03b-413a-8729-7d839026a7ec
